src/Version1/Models/TeamMember.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Version1.Models
{
    public class TeamMember
    {
        public string TeamId { get; set; }
        public Team Teams { get; set; }
        public string UserID { get; set; }
        public ApplicationUser Volunteers { get; set; }
    }
}

src/Version1/ViewModels/Team/NewLeaderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Version1.Models;

namespace Version1.ViewModels.Team
{
    public class NewLeaderViewModel
    {
        public string TeamId { get; set; }

        public List<Leader> Leaders { get; set; }

        public string LeaderId { get; set; }
    }
}

src/Version1/ViewModels/Team/TeamManageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Version1.ViewModels.Team
{
    public class TeamManageViewModel
    {
    }
}

src/Version1/ViewModels/Team/TeamMemberViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Version1.Models;
namespace Version1.ViewModels.Team
{
    public class TeamMemberViewModel
    {
        public List<Models.Team> Teams { get; set; }

        public List<ApplicationUser> Volunteers { get; set; }

        public List<TeamMember> Members { get; set; }
    }
}

src/Version1/Areas/Management/Controllers/TeamManageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Version1.Models;
using Version1.ViewModels.Team;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.Net.Http.Headers;
using Microsoft.AspNetCore.Hosting;
using System.IO;
namespace Version1.Controllers
{
    [Area("Management")]
   // [Authorize(Roles = "manager")]
    public class TeamManageController : Controller

    {
        private readonly ApplicationDbContext _context;
        TeamMemberViewModel memberViewModel = new TeamMemberViewModel();
        TeamMemberIndexViewModel memberIndexViewModel = new TeamMemberIndexViewModel();
        TeamDetailViewModel teamDetailViewModel = new TeamDetailViewModel();
        private IHostingEnvironment hostingEnv;
        public override void OnActionExecuting(ActionExecutingContext filterContext)
        {
              return;
            if(ModelState.Count == 0)
            {
                var areaname = filterContext.ActionDescriptor.RouteValues.Where(i => i.Key == "area").First().Value.ToString();
                var controllerName = filterContext.ActionDescriptor.RouteValues.Where(i => i.Key == "controller").First().Value.ToString();
                var actionName = filterContext.ActionDescriptor.DisplayName;
                // var userId = _userManager.GetUserAsync(HttpContext.User).Id.ToString();
                var userId = "";
                var FullControllerName = areaname + "/" + controllerName;
                var username = filterContext.HttpContext.User.Identity.Name;
                if(username == null)
                {
                    filterContext.Result = new ContentResult { Content = @"Sorry you don't have any aothrization." };
                    return;
                }
                string itemrole;
                List<string> aa = new List<string>();
                if(username == "")
                { filterContext.Result = new ContentResult { Content = @"Sorry you don't have any aothrization." }; return; }
                else if(username != "")
                {
                    //1.retrieving the role of the user from DB
                    userId = _context.Users.Where(aaa => aaa.UserName == username).First().Id.ToString();
                    foreach(var item in _context.UserRoles.Where(u => u.UserId == userId).ToList())
                    {
                        aa.Add(item.RoleId.ToString());
                    }
                    if(aa == null)
                    {
                        filterContext.Result = new ContentResult { Content = @"Sorry you don't have any aothrization." };
                        return;
                    }
                    else if(aa.Count == 0)
                    {
                        filterContext.Result = new ContentResult { Content = @"Sorry you don't have any aothrization." };
                        return;
                    }
                    if(_context.Authorization_Object.Where(N => N.ObjectType.ToUpper() == "FUNCTION").Where(N => N.ActionName.ToUpper() == actionName.ToUpper()).Where(N => N.FullControllerName.ToUpper() == FullControllerName.ToUpper()).Count() > 0)
                    {
                        //2.retrieving the role related to the ACTION from DB
                        var Object_ID = _context.Authorization_Object.Where(N => N.ObjectType.ToUpper() == "FUNCTION").Where(N => N.ActionName.ToUpper() == actionName.ToUpper()).Where(N => N.FullControllerName.ToUpper() == FullControllerName.ToUpper()).FirstOrDefault().ID.ToString();
                        List<Authorization_Object_Role> bb = _context.Authorization_Object_Role.Where(p => p.Authorization_Object_ID.ToString() == Object_ID).ToList();
                        //3.contrast the two roles,find if they are consistent 
                        if(bb == null)
                        {
                            filterContext.Result = new ContentResult { Content = @"Sorry you don't have any aothrization." };
                            return;
                        }
                        else if(bb.Count == 0)
                        {
                            filterContext.Result = new ContentResult { Content = @"Sorry you don't have any aothrization." };
                            return;
                        }
                        else
                        {
                            foreach(var item in bb)
                            {
                                itemrole = item.RoleID.ToString();
                                if(aa.Contains(itemrole) == true)
                                {
                                    filterContext.Result = filterContext.Result;
                                    return;
                                }
                            }
                        }
                    }
                }
                else
                {
                    filterContext.Result = new ContentResult { Content = @"Sorry you don't have any aothrization." };
                    return;
                }
            }
        }
        public TeamManageController(IHostingEnvironment env, ApplicationDbContext context)
        {
            this.hostingEnv = env;
            _context = context;
        }

        // GET: Teams
        public async Task<IActionResult> Index()
        {
            memberIndexViewModel.Teams = await _context.Teams.ToListAsync();
            memberIndexViewModel.TeamMembers = _context.TeamMembers.ToList();
            return View(memberIndexViewModel);
            // return View(await _context.Teams.ToListAsync());
        }

        // GET: Teams/Details/5
        public IActionResult Details(string id)
        {
            if(id == null)
            {
                return NotFound();
            }

            teamDetailViewModel.TeamId = id;
            teamDetailViewModel.TeamName = _context.Teams.Where(m => m.TeamId == id).First().TeamName;
            var memberlist = (from a in _context.TeamMembers
                              join b in _context.ApplicationUser on a.UserID equals b.Id
                              where a.TeamId == id
                              select new { volunteer_id = b.Id, volunteer_firstname = b.FirstName, volunteer_lastname = b.LastName }).Distinct();
            if(_context.Teams.Where(m => m.TeamId == id) != null)
            {
                if(_context.Teams.Where(m => m.TeamId == id).Count() > 0)
                {
                    teamDetailViewModel.LeaderId = _context.Teams.Where(m => m.TeamId == id).First().TeamLeaderID;
                    if(teamDetailViewModel.LeaderId != null)
                    {
                        teamDetailViewModel.LeaderFirstName = _context.ApplicationUser.Where(a => a.Id == teamDetailViewModel.LeaderId).First().FirstName;
                        teamDetailViewModel.LeaderLastName = _context.ApplicationUser.Where(a => a.Id == teamDetailViewModel.LeaderId).First().LastName;
                        teamDetailViewModel.LeaderContact = _context.ApplicationUser.Where(a => a.Id == teamDetailViewModel.LeaderId).First().PhoneNumber;
                        teamDetailViewModel.LeaderPortrait = _context.ApplicationUser.Where(a => a.Id == teamDetailViewModel.LeaderId).First().Portrait;
                    }

                }
            }

            List<TeamMemberDetailViewModel> dd = new List<TeamMemberDetailViewModel>();
            foreach(var item in memberlist)
            {
                TeamMemberDetailViewModel pp = new TeamMemberDetailViewModel();
                pp.VolunteerId = item.volunteer_id.ToString();
                pp.FirstName = item.volunteer_firstname.ToString();
                pp.LastName = item.volunteer_lastname.ToString();

                dd.Add(pp);

            }

            teamDetailViewModel.TeamMemberDetails = dd;


            if(teamDetailViewModel == null)
            {
                return NotFound();
            }

            return View(teamDetailViewModel);
        }

        // GET: Teams/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Teams/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Team Team)
        {
            Guid g;
            // Create and display the value of two GUIDs.
            g = Guid.NewGuid();
            Team.TeamId = g.ToString();
            
            if(ModelState.IsValid)
            {
                //upload Newsletter image
                string ImageGUID = Guid.NewGuid().ToString();
                var file = Request.Form.Files[0];
                var filename = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');
                if (filename != "")
                {
                    filename = ImageGUID + filename.Substring(filename.Length - 4, 4);
                    Team.TeamImage = filename;
                    filename = hostingEnv.WebRootPath + $@"\images\Teams\{filename}";
                    using (FileStream fs = System.IO.File.Create(filename))
                    {
                        file.CopyTo(fs);
                        fs.Flush();
                    }
                }
                   
                _context.Add(Team);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(Team);
        }

        // GET: Teams/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if(id == null)
            {
                return NotFound();
            }

src/Version1/Areas/Management/Views/TeamManage/Create.cshtml
@model Team

<form asp-area="Management" asp-controller="TeamManage" asp-action="Create" enctype="multipart/form-data">
    <div class="form-horizontal">
        <h4>Team</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="TeamName" class="col-md-2 control-label">Team Name</label>
            <div class="col-md-10">
                <input asp-for="TeamName" class="form-control" />
                <span asp-validation-for="TeamName" class="text-danger" />
            </div>
        </div>

        
        <div class="form-group">
            <label asp-for="TeamDescription" class="col-md-2 control-label">Team Description</label>
            <div class="col-md-10">
                <input asp-for="TeamDescription" class="form-control" />
                <span asp-validation-for="TeamDescription" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label   class="col-md-2 control-label">Team Picture</label>
            <div class="col-md-7" style="align-content:center">
                <input type="file" id="NewsImagepp" value="Open file" title="Open file" accept=".JPG,.JPEG,.GIF,.PNG,.bmp" name="NewsImagepp" />
                <img id="opop" src="~/images/Teams/" align="left" hidden="hidden" width="190" height="210" display=inline>

            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-area="Management" asp-controller="TeamManage" asp-action="Index">Back to List</a>
</div>


@section Scripts {
    <script src="//code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="//rawgithub.com/indrimuska/jquery-editable-select/master/dist/jquery-editable-select.min.js"></script>
    <script src="/lib/ckeditor/ckeditor.js"></script>
    <link href="//rawgithub.com/indrimuska/jquery-editable-select/master/dist/jquery-editable-select.min.css" rel="stylesheet">


    <script>
    $(function () {
        
   var  getobjectpath= function (file) {
        var url = null;
        if (window.createObjectURL != undefined) {
            url = window.createObjectURL(file)
        } else if (window.URL != undefined) {
            url = window.URL.createObjectURL(file)
        } else if (window.webkitURL != undefined) {
            url = window.webkitURL.createObjectURL(file)
        }
        return url
    };
   $("#NewsImagepp").change(function () {
        var imagepath = getobjectpath(this.files[0]);
        if (imagepath != "") {
            $("#opop").attr('src', imagepath);
            $("#opop").fadeIn(1000);
        }
   });
    });
    </script>
}

src/Version1/Areas/Management/Views/TeamManage/Delete.cshtml
@model Team


<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Team</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TeamName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TeamName)
        </dd>
    </dl>

    <form asp-area="Management" asp-controller="TeamManage" asp-route-id="@Model.TeamId" asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-area="Management" asp-controller="TeamManage" asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/Version1/Areas/Management/Views/TeamManage/Details.cshtml
@model Version1.ViewModels.Team.TeamDetailViewModel

<div class="row">
    <h3>Team: @Model.TeamName</h3>

    <br />

    <a asp-area="Management" asp-controller="TeamManage" asp-action="NewLeader" asp-route-id="@Model.TeamId" class="btn btn-default">Add/Change Leader</a>

    <br />

    <h4>Team Leader</h4>
    <div class="col-md-6">
        <img src="~/images/portrait/@Model.LeaderPortrait" align="left" height="210" width="190">
    </div>

    <div class="col-md-6">
        <ul class="list-group">
            <li class="list-group-item">
                First Name: @Model.LeaderFirstName
            </li>
            <li class="list-group-item">
                Last Name: @Model.LeaderLastName
            </li>
            <li class="list-group-item">
                Contact: @Model.LeaderContact
            </li>
        </ul>
    </div>

</div>

<div>
    <h4>Team Members</h4>

    <ul class="list-group">
        @foreach(var member in Model.TeamMemberDetails)
        {
            <li class="list-group-item">
                <a asp-area="Management" asp-controller="Volunteer" asp-action="Details" asp-route-id=@member.VolunteerId> @member.FirstName @member.LastName</a>
            </li>
        }
    </ul>
</div>
<br />

<a asp-area="Management" asp-controller="TeamManage" asp-action="TeamMember" asp-route-id="@Model.TeamId" class="btn btn-default">Add New Member</a>

<br />

@*<dl class="dl-horizontal">
    <dt>
    </dt>
    <dd align="center" style="font-size:xx-large">
        @Html.DisplayFor(model => model.TeamName)

    </dd>
    <dd></dd>
    <dt style="font-size:medium">
        Team Leader
    </dt>
    <dd>
        <div><img src="~/images/portrait/@Model.LeaderPortrait" align="left" height="210" width="190" display=inline> </div>
        <div>
            <dl style="float:left;"><dt style="font-size:medium">Leader Name:</dt><dd>@Model.LeaderFirstName @Model.LeaderLastName</dd></dl>
            <dl style="float:left;"><dt style="font-size:medium">Leader Contact:</dt><dd>@Model.LeaderContact</dd></dl>
        </div>
    </dd>*@
@*<dt style="font-size:medium">
            Mumbers List
        </dt>
        <dd>
            (sum:
            @Model.TeamMemberDetails.Count @{ string p;}
            @{if(Model.TeamMemberDetails.Count > 1)
                {
                    p = "members";
                }
                else
                {
                    p = "member";
                }
            }
            @p)
        </dd>

        @{ int i = 0;}
        @foreach(var item in Model.TeamMemberDetails)
        {

            <dd>
                @{i = i + 1;}
                @i:<a asp-area="Management" asp-controller="Volunteer" asp-action="Details" asp-route-id=@item.VolunteerId>@item.FirstName @item.LastName </a>
            </dd>
                    }
        <dd>  <a asp-area="Management" asp-controller="TeamManage" asp-action="TeamMember" asp-route-id="@Model.TeamId">Add New Member</a> </dd>

        </dl>
    </div>*@

<div>
    <a asp-area="Management" asp-controller="TeamManage" asp-action="Edit" asp-route-id="@Model.TeamId" class="btn btn-default">Edit</a>
    <a asp-area="Management" asp-controller="TeamManage" asp-action="Index" class="btn btn-default">Back to List</a>
</div>

@section scripts{
    <script type="text/javascript">

        $(document).ready(function () {
            $('.btneditAuthorization').click(function (event) {
                event.preventDefault();
                if ($(this).attr('value') == 'true') {
                    $(this).attr('value', 'false');
                    $(this).removeClass('glyphicon-ok').addClass('glyphicon-remove');
                }
                else if ($(this).attr('value') == 'false') {
                    $(this).attr('value', 'true');
                    $(this).removeClass('glyphicon-remove').addClass('glyphicon-ok');
                }
            });
        });
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#formAuthorizationUpdate').on('click', '#submit', function (event) {
                event.preventDefault();
                var dict = [];
                $('.btneditAuthorization').each(function (index) {
                    if ($(this).attr('value') == 'true') {
                        var item = { RoleID: $(this).attr('itemid'), Authorization_Object_ID: $(this).attr('name') };
                        dict.push(item);
                    }
                    else { }
                });
                var postUrl = '/Management/Authorization_Object_Role/Update';
                // Post and return to the given view is there is nothing to return.
                $.post(postUrl, { AuthorizationDone: dict }, function (result) {
                    window.location.assign("/Management/Authorization_Object_Role/Index");
                    alert('You have finished change!');
                });
            });
        });

    </script>

}

src/Version1/Areas/Management/Views/TeamManage/Edit.cshtml
@model Team

<form class="form-horizontal" asp-area="Management" asp-controller="TeamManage" asp-route-id=@Model.TeamId asp-action="Edit" enctype="multipart/form-data">
    <h4>Edit Team</h4>
    <hr />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <input type="hidden" asp-for="TeamId" />

    <div class="form-group">
        <label asp-for="TeamName" class="col-md-2 control-label">Team Name</label>
        <div class="col-md-10">
            <input asp-for="TeamName" class="form-control" />
            <span asp-validation-for="TeamName" class="text-danger" />
        </div>
    </div>

    <div class="form-group">
        <label   class="col-md-2 control-label"> Team Photo</label>
        <div class="col-md-10">
            <input type="file" id="NewsImagepp" value="Open file" title="Open file" accept=".JPG,.JPEG,.GIF,.PNG,.bmp" name="NewsImagepp" />
            <img id="opop" src="~/images/Teams/@Model.TeamImage" align="left" width="190" height="210" display=inline  >
            <input type="hidden" asp-for="TeamImage" />
        </div>   
            
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</form>

<div>
    <a asp-area="Management" asp-controller="TeamManage" asp-action="Index">Back to List</a>
</div>


@section Scripts {
    <script src="//code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="//rawgithub.com/indrimuska/jquery-editable-select/master/dist/jquery-editable-select.min.js"></script>
    <script src="/lib/ckeditor/ckeditor.js"></script>
    <link href="//rawgithub.com/indrimuska/jquery-editable-select/master/dist/jquery-editable-select.min.css" rel="stylesheet">


    <script>
    $(function () {
     
   var  getobjectpath= function (file) {
        var url = null;
        if (window.createObjectURL != undefined) {
            url = window.createObjectURL(file)
        } else if (window.URL != undefined) {
            url = window.URL.createObjectURL(file)
        } else if (window.webkitURL != undefined) {
            url = window.webkitURL.createObjectURL(file)
        }
        return url
    };
   $("#NewsImagepp").change(function () {
        var imagepath = getobjectpath(this.files[0]);
        if (imagepath != "") {
            $("#opop").hide;
            $("#opop").attr('src', imagepath);
            $("#opop").fadeIn(1000);
        }
   });
    });
    </script>
}

src/Version1/Areas/Management/Views/TeamManage/Index.cshtml
@model Version1.ViewModels.Team.TeamMemberIndexViewModel
<br/>
<p>
    <a class="btn btn-default" asp-area="Management" asp-controller="TeamManage" asp-action="Create">Create New</a>
</p>
<table    id="Teamstable" class="display" cellspacing="0" width="100%">
    <thead>
         <tr>
            <th>
                Team name
            </th>
            <th>Members amount</th><th></th>
         </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Teams){
            <tr>
                <td>
                    @item.TeamName
                </td>
                <td>
                    @{ int u = 0;
                        if (item != null)
                        {
                            if (Model.TeamMembers.Where(t => t.TeamId == item.TeamId) == null)
                            {
                                u = 0;
                            }
                            else
                            {
                                u = Model.TeamMembers.Where(t => t.TeamId == item.TeamId).Count();
                            }
                        }
                        @u
                    }
                </td>
                <td>
                    <a asp-area="Management" asp-controller="TeamManage" asp-action="Edit" asp-route-id="@item.TeamId ">Edit</a> |
                    <a asp-area="Management" asp-controller="TeamManage" asp-action="Details" asp-route-id="@item.TeamId">Details</a> |
                    <a asp-area="Management" asp-controller="TeamManage" asp-action="Delete" asp-route-id="@item.TeamId">Delete</a>
                </td>
            </tr>
                        }
    </tbody>
</table>
 
@section Scripts {
    <link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.10.12/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" charset="utf8" src="http://cdn.datatables.net/1.10.12/js/jquery.dataTables.js"></script>
<script>
    $(document).ready(function () {
        
        $('#Teamstable').DataTable({ "columnDefs": [{ "className": "dt-center", "targets": "_all" }] });
     });
</script>}

src/Version1/Areas/Management/Views/TeamManage/NewLeader.cshtml
@model Version1.ViewModels.Team.NewLeaderViewModel

<form class="form-horizontal" id="formnewleader" asp-route-area="Management" asp-controller="TeamManage" asp-action="ConfirmLeader" asp-route-id="@Model.LeaderId" method="post" role="form">
    <input id="leadid" hidden asp-for="LeaderId" />
    <input id="teamid" hidden asp-for="TeamId" />
    <dl>
        <dt>
            @foreach(var item in Model.Leaders)
            {
                <div id="ll" class="btneditSelectLeader btn btn-sm glyphicon glyphicon-remove" itmeid="@item.LeaderId" role="radio" value="false" style="font-size:x-large;font-weight:bold;">
                    @item.FirstName @item.LastName
                </div>
            }
        </dt>
    </dl>

    <input type="submit" class="btn btn-default btnSubmit" role="button" value="Save Configuration" />
</form>
@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('.btneditSelectLeader').click(function (event) {
                event.preventDefault();
                if ($(this).attr('value') == 'true') {
                    $(this).attr('value', 'false');
                    $(this).removeClass('glyphicon-ok').addClass('glyphicon-remove');
                    $('#leadid').val('');
                }
                else if ($(this).attr('value') == 'false') {
                    $('.btneditSelectLeader').attr('value', 'false');
                    $('.btneditSelectLeader').removeClass('glyphicon-ok').addClass('glyphicon-remove');
                    $(this).attr('value', 'true');
                    $(this).removeClass('glyphicon-remove').addClass('glyphicon-ok');
                    $('#leadid').val($(this).attr('itmeid'));

                }
            });
        });
    </script>
}

src/Version1/Areas/Management/Views/TeamManage/TeamMember.cshtml
@model Version1.ViewModels.Team.TeamMemberViewModel

<h1>Configuration of Team and Volunteer</h1>
<a asp-area="Management" asp-controller="Teams" asp-action="Create">Add a new Team</a>
<form id="teammumber" asp-area="Management" asp-controller="TeamManage" asp-action="TeamMember" method="post" role="form">
    <table id="teamMumbertable" class="table">
        <thead>
            <tr>
                <th>Volunteers/Teams</th>
                @foreach(var item in Model.Teams)
                {
                    <th>
                        <a asp-area="Management" asp-controller="TeamManage" asp-action="Details" asp-route-id="@item.TeamId"> @item.TeamName   </a>
                    </th>
                }
            </tr>
        </thead>
        <tbody>
            @foreach(var p in Model.Volunteers)
            {
                <tr>
                    <td>
                        <a asp-area="Management" asp-controller="Volunteer" asp-action="Details" asp-route-id="@p.Id">@p.FirstName @p.LastName </a>
                    </td>
                    @foreach(var k in Model.Teams)
                    {
                        <td>

                            @if(Model.Members.Where(i => i.TeamId == k.TeamId).Where(j => j.UserID == p.Id).ToList().Count > 0)
                            {
                                <div class="btneditTeammumber btn btn-sm glyphicon glyphicon-ok" role="checkbox" value="true" itemid="@p.Id" name="@k.TeamId"></div>
                            }
                            else
                            {
                                <div class="btneditTeammumber btn btn-sm glyphicon glyphicon-remove" role="checkbox" value="false" itemid="@p.Id" name="@k.TeamId"></div>
                            }
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
    <button id="submit" class="btn btn-default btnSubmit" role="button">Save Team-Mumber</button>
</form>
@section scripts{
    <script type="text/javascript">

        $(document).ready(function () {
            $('.btneditTeammumber').click(function (event) {
                event.preventDefault();
                if ($(this).attr('value') == 'true') {
                    $(this).attr('value', 'false');
                    $(this).removeClass('glyphicon-ok').addClass('glyphicon-remove');
                }
                else if ($(this).attr('value') == 'false') {
                    $(this).attr('value', 'true');
                    $(this).removeClass('glyphicon-remove').addClass('glyphicon-ok');
                }
            });
        });

    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#teammumber').on('click', '#submit', function (event) {
                event.preventDefault();
                var dict = [];
                $('.btneditTeammumber').each(function (index) {
                    if ($(this).attr('value') == 'true') {
                        var item = { TeamId: $(this).attr('name'), UserID: $(this).attr('itemid') };
                        dict.push(item);
                    }
                    else { }
                });
                var postUrl = '/Management/TeamManage/Update';
                // Post and return to the given view is there is nothing to return.
                $.post(postUrl, { Members: dict }, function (result) {
                    window.location.assign("/Management/TeamManage/Index");
                    // window.history.go(-1).reload();
                    alert('You have finished change!');

                });

            });
        });

    </script>
}